---

- name: Development Tools Playbook
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:

    - name: install packages outils de developpement
      apt:
        pkg:
        - npm
        update_cache: yes

    - name: install packages outils de developpement
      snap:
        name:
          - postman


