---

- name: Music Tools Playbook
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:


  - name: Add Spotify official GPG key
    shell:
      cmd: curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add -
  - name: set up spotify repository
    shell:
      cmd: echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list


  - name: install packages
    apt:
      pkg:
        - clementine
        - spotify-client
      update_cache: yes


