---

- name: Install Grafana agent 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:

    - name: Install graphana agent
      shell:
        cmd: ARCH="amd64" GCLOUD_STACK_ID="523525" GCLOUD_API_KEY="eyJrIjoiNGE0OGIxZjE5ZjdlNWM5OTA0NWRkNjU4OTAwMDNlYzJiOWVkZDViYyIsIm4iOiJzdGFjay01MjM1MjUtZWFzeXN0YXJ0LWdjb20iLCJpZCI6NzgzNzQ4fQ==" GCLOUD_API_URL="https://integrations-api-eu-west.grafana.net" /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/release/production/grafanacloud-install.sh)"
    - name: install grafana-agent config 
      copy:
        src: config/grafana/grafana-agent.yaml
        dest: /etc/grafana-agent.yaml
    - name: Reload grafana agent
      ansible.builtin.systemd:
        name: grafana-agent.service
        state: restarted
#sudo systemctl restart grafana-agent.service