---
- hosts: localhost
  remote_user: root
  connection: local
  tasks:
    - name: user remi
      user:
        name: remi
        groups: root,sudo,audio,www-data,docker

- name: Local Getting Started First Playbook
  connection: local
  gather_facts: false
  hosts: localhost
  remote_user: remi
  tasks:
    - name: generate SSH key
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no