---
- hosts: bananapi
  remote_user: root
  tasks:
    - name: install packages
      apt:
        pkg:
        - cmus
        - ffmpeg
        - python3-pip
        - docker.io
        - docker-compose
        - apparmor
        update_cache: yes

