---
- hosts: bananapi
  remote_user: root
  tasks:
    - name: create user bi
      user:
        name: bi
        password: $6$mysecretsalt$KwBXMXgW1BP9mgMTLC3xHNKh6hIBR.kproH3L4aWc0q5x.tL2E74Maw5J9QXknqyWrxV9uoSKbnb7utwbFd/81
        groups: root,sudo,audio,docker
        shell: /bin/bash
        home: /home/bi
    - name: install asoundrc 
      copy:
        src: asoundrc
        dest: /home/bi/.asoundrc

- hosts: bananapi
  remote_user: bi
  tasks:
    - name: generate SSH key
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no