---

- name: Local Getting Started First Playbook
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:

  - name: Add Docker’s official GPG key
    shell:
      cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: set up the stable docker repository
    shell:
      cmd: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
  - name: INSTALL DOCKER ENGINE - COMMUNITY
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      update_cache: yes
  - name: add user remi to group docker
    user:
      name: remi
      groups: docker
      append: yes
  - name: install docker compose
    shell:
      cmd: curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - name: install docker compose
    shell:
      cmd: chmod +x /usr/local/bin/docker-compose
