---

- name: Photo tools Playbook
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:

    # sudo add-apt-repository ppa:f-spot/f-spot-ppa
    # - apt_repository:
    #     repo: ppa:f-spot/f-spot-ppa
    #     state: present

    - apt_repository:
        repo: ppa:ubuntuhandbook1/avidemux
        state: present

    - apt_repository:
        repo: ppa:ubuntuhandbook1/darktable
        state: present

    - name: install packages from URL
      apt:
        # les codes vuescan se trouvent dans keepass
        deb: https://www.hamrick.com/files/vuex6497.deb
        # Emplacement de la base xnview : /mnt/DATA/nextcloud-sync/remi/Photos/.tools/xnview/
        # à paramétrer dans le menu outils/paramètres/intégration/chemins
        deb: https://download.xnview.com/XnViewMP-linux-x64.deb

    - name: install packages
      apt:
        pkg:
        - tesseract-ocr
        - tesseract-ocr-fra
        - imagemagick
        - simple-scan
        - gimp
        - avidemux2.7-qt5
        - digikam
        - kphotoalbum
        - gimagereader
        - darktable
        update_cache: yes